name: terraform-ci

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  static-checks:
    name: Fmt · Validate · TFLint · tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (sin backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint init
        run: tflint --init

      - name: TFLint run
        run: tflint

      # tfsec usando Docker (no dependemos de action/tag)
      - name: Run tfsec (Docker)
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/src" \
            aquasec/tfsec/tfsec:latest \
            /src --format sarif --out /src/tfsec.sarif
        continue-on-error: true

      - name: Upload tfsec SARIF
        if: always()   # intenta subir aunque tfsec falle
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
