name: terraform-ci

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  security-events: write   # para subir el SARIF de tfsec
  actions: read

jobs:
  static-checks:
    name: Fmt · Validate · TFLint · tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (sin backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint init
        run: tflint --init

      - name: TFLint run
        run: tflint

      - name: Setup tfsec
        uses: aquasecurity/setup-tfsec@v1

      - name: Run tfsec
        run: tfsec --format sarif --out tfsec.sarif .
        continue-on-error: true

      - name: Upload tfsec SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
